version: '3.5'

services:
  backend:
    container_name: app_backend
    restart: unless-stopped
    build: ./backend
    command: npm run start
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db_app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
            

  db_app:
    container_name: db_app
    restart: unless-stopped
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
